### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by Nakroma** [nexus-devs/nexus-stats#16]
Required unit tests:

- [X] Requests
- [X] Item list
- [ ] Statistics
  - [X] General stats
  - [X] Anti spoofing
  - [ ] Ignoring / Extreme behaviour

**Comment by Kaptard** [comment]
Also add the following:
- [ ] Statistics subscriptions (publishes on new request)
- [ ] Caching
  - [ ] Statistics Cache
  - [ ] Item Cache 
  - [ ] Item List Cache
